// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtmczzqveablmemifwpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0bWN6enF2ZWFibG1lbWlmd3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjA5MTIsImV4cCI6MjA2NDM5NjkxMn0.vjbXVPjYaig2S5royq0jLmuLa_IRdjuUG3EJ98lWzz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);